services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - app_network
    restart: unless-stopped
    shm_size: 256mb

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - app_network
    depends_on:
      - db
    restart: unless-stopped

  web:
    build: .
    command: bash -c "dos2unix /app/.build.sh && chmod +x /app/.build.sh && /app/.build.sh"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge